name: CreeperRecover
version: 1.0.12
main: de.rafael.plugins.creeper.recover.CreeperRecover
api-version: 1.19
description: Recovers all destroyed blocks by Creeper or other Entities
author: HttpRafa
commands:
  recover:
    description: Command to control the plugin