name: "Build creeper-recover"
on: [ "push" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build
      - name: Upload Jars
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: |
            folia/build/libs/*.jar
            spigot/build/libs/*.jar
